// Documentation Registry
// This file acts as a simple database for the documentation files.
const DOC_REGISTRY = {
    "blocks": [
        { name: "Overview", path: "blocks/overview.md" },
        { name: "Druppie UI", path: "blocks/druppie_ui.md" },
        { name: "Druppie Core", path: "blocks/druppie_core.md" },
        { name: "CI/CD Pipeline (Tekton)", path: "blocks/ci_cd_tekton.md" },
        { name: "Database (PostgreSQL)", path: "blocks/database_postgres.md" },
        { name: "Vector Database (Qdrant)", path: "blocks/database_qdrant.md" },
        { name: "Geo-Database (PostGIS)", path: "blocks/database_postgis.md" },
        { name: "GitOps & State (Flux)", path: "blocks/gitops_flux.md" },
        { name: "Observability (PLG Stack)", path: "blocks/observability_plg.md" },
        { name: "Git & Versiebeheer (Gitea)", path: "blocks/git_gitea.md" },
        { name: "Container Registry (Harbor)", path: "blocks/container_registry.md" },
        { name: "Traceability (Tempo & OTEL)", path: "blocks/traceability_otel.md" },
        { name: "IAM (Keycloak & Azure AD)", path: "blocks/iam_keycloak.md" },
        { name: "Data Lake (MinIO)", path: "blocks/data_lake_minio.md" },
        { name: "Infrastructure as Code (Terraform)", path: "blocks/iaas_terraform.md" },
        { name: "AI Dataset Versioning (DVC)", path: "blocks/data_versioning_dvc.md" },
        { name: "Drone Mapping (WebODM)", path: "blocks/drone_pipeline_odm.md" },
        { name: "AI Anonymizer (YOLOv8)", path: "blocks/ai_anonymizer_yolo.md" },
        { name: "Workflow Engine (Argo)", path: "blocks/workflow_argo.md" },
        { name: "API Gateway (Kong)", path: "blocks/api_gateway_kong.md" },
        { name: "Architectuur (Archi)", path: "blocks/architecture_archi.md" },
        { name: "GIS Desktop (QGIS)", path: "blocks/gis_qgis.md" },
        { name: "GIS Server (GeoServer)", path: "blocks/gis_geoserver.md" },
        { name: "GIS Portal (GeoNode)", path: "blocks/gis_geonode.md" },
        { name: "Policy Enforcement (Kyverno)", path: "blocks/policy_kyverno.md" },
        { name: "Scanning & Compliance (Trivy)", path: "blocks/security_scanning_trivy.md" },
        { name: "Code Quality (SonarQube)", path: "blocks/code_quality_sonarqube.md" },
        { name: "AI Video (ComfyUI)", path: "blocks/ai_video.md" },
        { name: "AI Audio (TTS)", path: "blocks/ai_audio.md" },
        { name: "Media & Brand", path: "blocks/brand_management.md" },
    ],
    "agents": [
        { name: "Overview", path: "agents/overview.md" },
        { name: "Router", path: "agents/router.md" },
        { name: "Planner", path: "agents/planner.md" },
        { name: "Compliance", path: "agents/compliance.md" },
        { name: "Architect", path: "agents/architect.md" },
        { name: "Business Analyst", path: "agents/business_analyst.md" },
        { name: "Data Scientist", path: "agents/data_scientist.md" },

        { name: "Infrastructure Engineer", path: "agents/infrastructure-engineer.md" },
        { name: "Skill Dispatcher", path: "agents/skill_executor.md" },
        { name: "Tester", path: "agents/tester.md" },
        { name: "Video Content Creator", path: "agents/video-content-creator.md" },
        { name: "Native Workflow Engineer", path: "agents/native-converter.md" },
        { name: "Build Agent", path: "agents/build_agent.md" },
        { name: "Run Agent", path: "agents/run_agent.md" },
        { name: "Developer", path: "agents/developer.md" },
        { name: "Audio Creator", path: "agents/audio-creator.md" },
        { name: "Image Creator", path: "agents/image-creator.md" },
        { name: "Video Creator", path: "agents/video-creator.md" },
        { name: "MCP Specialist", path: "agents/mcp_agent.md" }
    ],
    "skills": [
        { name: "Overview", path: "skills/overview.md" },
        { name: "Golang", path: "skills/golang.md" },
        { name: "Kubernetes Ops", path: "skills/kubernetes.md" },
        { name: "Mermaid", path: "skills/mermaid.md" },
        { name: "Node.js", path: "skills/nodejs.md" },
        { name: "Python", path: "skills/python.md" },
        { name: "Check Block Status", path: "skills/check-block-status.md" },
        { name: "WCAG 2.1 AA", path: "skills/WCAG-2-1-AA.md" },
        { name: "Ask Questions", path: "skills/ask_questions.md" },
        { name: "Audio Review", path: "skills/audio-review.md" },
        { name: "Content Merge", path: "skills/content-merge.md" },
        { name: "Content Review", path: "skills/content-review.md" },
        { name: "Creative Writing", path: "skills/creative-writing.md" },
        { name: "Expand Loop", path: "skills/expand_loop.md" },
        { name: "Image Review", path: "skills/image-review.md" },
        { name: "Main Agent Logic", path: "skills/main-agent.md" },
        { name: "Orchestration", path: "skills/orchestration.md" },
        { name: "Sub-Agent Logic", path: "skills/sub-agent.md" },
        { name: "Video Review", path: "skills/video-review.md" }
    ],
    "research": [
        { name: "Overview", path: "research/overview.md" },
        { name: "Copilot Integratie", path: "research/copilot.md" },
    ],

    "compliance": [
        { name: "Overview", path: "compliance/overview.md" },
        { name: "Goed Bestuur (Code)", path: "compliance/good_governance.md" },
        { name: "Digitaal Toegankelijk", path: "compliance/digitaal_toegangkelijk.md" },
        { name: "BIO & NIS2", path: "compliance/bio_nis2.md" },
        { name: "Data Act", path: "compliance/data_act.md" },
        { name: "AI Act (EU & UvW)", path: "compliance/ai_act.md" },
        { name: "AI Register (Algoritmeregister)", path: "compliance/ai_register.md" },
        { name: "IAM", path: "compliance/iam.md" }
    ],
    "mcp": [
        { name: "Overview", path: "mcp/overview.md" },
        { name: "Microsoft & Azure", path: "mcp/microsoft.md" },
        { name: "Open Source Tools", path: "mcp/opensource.md" },
        { name: "Web Design", path: "mcp/shadcn.md" },
        { name: "Plan FS Template", path: "mcp/plan_fs_template.md" }
    ],
    "design": [
        { name: "Overview", path: "design/overview.md" },
        { name: "Bouwblok Definities", path: "design/bouwblok_definities.md" },
        { name: "Build Plane", path: "design/build_plane.md" },
        { name: "Compliance Layer", path: "design/compliance_layer.md" },
        { name: "Knowledge Bot", path: "design/knowledge_bot.md" },
        { name: "Mens in de Loop", path: "design/mens_in_de_loop.md" },
        { name: "Traceability DB", path: "design/traceability_db.md" },
        { name: "MCP Server Host", path: "design/mcp_server.md" },
        { name: "Policy Engine", path: "design/policy_engine.md" },
        { name: "Runtime Interface", path: "design/runtime.md" },
        { name: "Druppie Core", path: "design/druppie_core.md" },
        { name: "Druppie UI", path: "design/druppie_ui.md" },
        { name: "ARCH: Agentic Patterns", path: "design/agentic_patterns.md" },
        { name: "TO: Hybride Architectuur (K8s)", path: "design/hybrid_cluster_architecture.md" },
        { name: "TO: Component Interactie (Build->Run)", path: "design/component_interaction.md" },
        { name: "TO: Data Lifecycle & Versiebeheer", path: "design/data_lifecycle_drone.md" },
        { name: "TO: Deployment & Rolling Updates", path: "design/deployment_strategies.md" },
        { name: "TO: IAM & Keycloak Interactie", path: "design/iam_keycloak_interaction.md" },
        { name: "TO: Automated Rebuild (Watchdog)", path: "design/automated_rebuild.md" },
        { name: "TO: Secure Agentic RAG Network", path: "design/agentic_rag_network.md" },
        { name: "TO: Continuous Compliance & Lifecycle", path: "design/compliance_lifecycle_monitoring.md" },
        { name: "TO: Automated Testing & Documentation", path: "design/automated_testing_docs.md" },
        { name: "TO: Builder Agent", path: "design/builder_agent.md" },
        { name: "TO: Foundry", path: "design/foundry.md" },
        { name: "TO: Runtime", path: "design/runtime_implementation.md" },
        { name: "TO: Role Based Access Control (RBAC)", path: "design/rbac.md" },
        { name: "TO: MCP Interface", path: "design/mcp_interface.md" },
        { name: "TO: Dynamic Slot", path: "design/dynamic_slot.md" },
        { name: "TO: Git", path: "design/git.md" },
        { name: "FO: Vergunning zoeker", path: "design/vergunning_zoeker.md" },
        { name: "FO: Exoten Detectie", path: "design/exoten_detectie.md" },
        { name: "FO: AI Video Workflow", path: "design/ai_video_workflow.md" },
        { name: "FO: Drone Planner", path: "design/drone_planner.md" },
        { name: "SPEC: Druppie", path: "design/druppie_spec.md" },
    ],
    "scripts": [
        { name: "Overview", path: "script/overview.md" },
        { name: "Druppie CLI", path: "script/druppie.sh" },
        { name: "Install Kubernetes (RKE2/k3d)", path: "script/install_k8s.sh" },
        { name: "Platform Bootstrap (Base)", path: "script/setup_dev_env.sh" },
        { name: "Data Tools (Gitea/MinIO/Qdrant)", path: "script/setup_data_tools.sh" },
        { name: "IAM Setup (Keycloak)", path: "script/setup_iam.sh" },
        { name: "Observability (LGTM)", path: "script/setup_observability.sh" },
        { name: "GIS Tools (GeoServer)", path: "script/setup_gis.sh" },
        { name: "Security Tools (Trivy)", path: "script/setup_security_tools.sh" },
        { name: "Install Druppie Core", path: "script/install_druppie.sh" },
        { name: "Uninstall Kubernetes", path: "script/uninstall_k8s.sh" }
    ],
    "tools": [
        { name: "Overview", path: "tools/overview.md" },
        { name: "Keycloak (IAM)", path: "tools/keycloak.md" },
        { name: "Grafana (Obs)", path: "tools/grafana.md" },
        { name: "Gitea (Git)", path: "tools/gitea.md" },
        { name: "MinIO (S3)", path: "tools/minio.md" },
        { name: "pgAdmin (DB UI)", path: "tools/pgadmin.md" },
        { name: "GeoServer (GIS)", path: "tools/geoserver.md" },
        { name: "GeoNode (GIS CMS)", path: "tools/geonode.md" },
        { name: "NodeODM (Drone Images)", path: "tools/nodeodm.md" },
        { name: "Rancher (K8s UI)", path: "tools/rancher.md" },
        { name: "Kong Manager (API Gateway)", path: "tools/kong.md" }
    ],
    "general": [
        { name: "Project Readme", path: "README.md" },
        { name: "Het Verhaal Druppie", path: "story/story.md" },
        { name: "Project Brief", path: "story/project_brief.md" },
        { name: "Testing Prompts", path: "story/test.md" },
        { name: "License (MIT)", path: "LICENSE.md" },
    ]
};
